services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
  
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_HOST: ${VITE_BACKEND_HOST}
        VITE_BACKEND_PORT: ${VITE_BACKEND_PORT}
        VITE_BACKEND_PROTOCOL: ${VITE_BACKEND_PROTOCOL}
        VITE_MAPBOX_TOKEN: ${VITE_MAPBOX_TOKEN}
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend